apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todo-pod-reader
  namespace: todo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: todo
