apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgresql-db
  name: postgresql-db
  namespace: todo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
