apiVersion: v1
data:
  postgresql.conf: | 
    listen_addresses = '*'
    max_connections = 100
    shared_buffers = 128MB
    dynamic_shared_memory_type = posix
    synchronous_commit = off
    max_wal_size = 1GB
    min_wal_size = 80MB
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    log_timezone = 'Etc/UTC'
    datestyle = 'iso, mdy'
    timezone = 'Etc/UTC'
    lc_messages = 'en_US.utf8'
    lc_monetary = 'en_US.utf8'
    lc_numeric = 'en_US.utf8'
    lc_time = 'en_US.utf8'
    default_text_search_config = 'pg_catalog.english'
kind: ConfigMap
metadata:
  name: postgresql-conf
  namespace: todo