apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis-storage
  name: redis-storage
  namespace: todo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
