apiVersion: v1
kind: Service
metadata:
  labels:
    app: todoapi
  name: todoapi-service
  namespace: todo
spec:
  selector:
    app: todoapi-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
