apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todoapi-deployment
  name: todoapi-deployment
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapi-app
  template:
    metadata:
      labels:
        app: todoapi-app
    spec:
      containers:
        - name: todoapi
          env:
            - name: Database__Host
              value: todoapi-postgres-service
            - name: Redis__Host
              value: todoapi-redis-service
            - name: ASPNETCORE_URLS
              value: http://+:8080
          image: todoapi:0.0.1
          ports:
            - containerPort: 8080        
      restartPolicy: Always
      initContainers:
      - name: init-postgres
        image: busybox:1.28
        command: ['sh', '-c', "echo waiting for postgres; until nslookup todoapi-postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do sleep 1; done"]
      - name: init-redis
        image: busybox:1.28
        command: ['sh', '-c', "echo waiting for redis; until nslookup todoapi-redis-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do sleep 1; done"]
