apiVersion: v1
kind: Service
metadata:
  name: {{ include "todoapi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todoapi.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "todoapi.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
