apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources: {{ toYaml .Values.resources | nindent 4 }}
