# only for setting up integration tests
version: "3.4"

services:
  postgres:
    image: postgres:alpine3.16
    restart: always
    environment:
      - POSTGRES_DB=TodoDb
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=p@ssw0rd
    ports:
      - 5432:5432
    volumes:
      - postgresql-db:/var/lib/postgresql/data
  redis:
    image: redis:bullseye
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1
    volumes:
      - redis-storage:/data
volumes:
  postgresql-db:
    driver: local
  redis-storage:
    driver: local